### ISSUE TITLE
Results are not reproducible with seed option

### ISSUE THREAD

**Issue by KristianBerg** [exoji2e/hashcode-template#14]
Using -s option to specify seed does not reproduce results (when applied to pizza.py)

To reproduce:
python3 main.py --nsspec pizza:score:solve example_pizza 
python3 main.py --nsspec pizza:score:solve -s <seed> example_pizza

**Comment by exoji2e** [comment]
Thanks for catching this. Found the error, the seed is taken as an int when generated and a string when given from arguments `-s 100`. Fixed in 2fe106309cec654289c73a217df904a509264b59 :)
