### ISSUE TITLE
Make it possible to force outputing the submission with a flag

### ISSUE THREAD

**Issue by exoji2e** [exoji2e/hashcode-template#17]
This would have been nice if the scoring function is broken or not implemented yet.

**Comment by ahnlabb** [comment]
Should already be supported by the '--ignore' argument. Please verify.

**Comment by exoji2e** [comment]
Well, it won't print the solution, since the score will default to 0.

**Comment by ahnlabb** [comment]
Ok, I'm refactoring the process function. I will include this.
