### ISSUE TITLE
Cache data from precomputation

### ISSUE THREAD

**Issue by ahnlabb** [exoji2e/hashcode-template#2]
The precomputation step of the problems may take considerable time.  I suggest adding a precompute function that caches the result.

Proposal:
- use `pickle` library
- add command line option to clear cache

**Comment by exoji2e** [comment]
I'm thinking:
+ We probably only want to clear the cache for a specific dataset.
+ I guess we'd have a function ```get_cached(name, function)``` That would search for the cached result in ```cache/dataset/name``` If it can't find anything it calls function and saves it on the path.

**Comment by exoji2e** [comment]
We kind of know how to do this, however its unclear if it ever will be useful, since its slow to read from file
