### ISSUE TITLE
Remove setup.sh

### ISSUE THREAD

**Issue by ahnlabb** [exoji2e/hashcode-template#3]
Having a setup bash file seems reasonable however the current function of `setup.sh` can be handled in a safer and (in my opinion) cleaner manner (e.g. `try` statement)

**Comment by ahnlabb** [comment]
Replacing the creation of directories (currently just `ans`) is not as easy as fixing the potentially non-existent files. In python3 it's simple, we can use `pathlib` or `os.makedirs` with `exists_ok=true`. To support python2 and avoid race conditions we have to write our own function or use the backport of pathlib (pathlib2).

**Comment by exoji2e** [comment]
Maybe a simpler solution is to make sure there is an ```ans``` folder with a readme inside?

**Comment by exoji2e** [comment]
Go ahead and add a similar file to ```in/README.md``` in the ```ans```-folder and rm ```setup.sh```.

However we might want the creation of dictionaries for #2 . I guess we can solve that as well by saving cached files on the format ```cache/testcase-cachedfunction.pkl```

**Comment by exoji2e** [comment]
Removed setup.sh as well.
