### ISSUE TITLE
Adding testing

### ISSUE THREAD

**Issue by ahnlabb** [exoji2e/hashcode-template#5]
To simplify development we should probably have some basic tests. Could the code for the practice problem be refactored and then used for this?

**Comment by exoji2e** [comment]
Hopefully. Maybe we can mock the scoring function to test the ```process``` function. I see one problem though; right now we assume it's a maximization-problem. What if we actually get a minimization-problem?

But I guess we can have a test framework based on the practice problem, then test how much we like it on another problem. I suggest on the amazon delivery problem from 2016.

**Comment by exoji2e** [comment]
```pizza.py``` works as testing currently. We might still want to add more, but we can at least test all args currently.
